### ISSUE TITLE
Role of Dr. Smith as Supervisor

### ISSUE THREAD

**Issue by littleappledev** [sgao1995/Cat-and-Mouse-Game#11]
(Notes from Meeting #1) 
-  Weekly meetings (Fridays @ 12:00) will NOT take place unless scheduled by Development Team and agreed upon by Dr. Smith
  -  Meeting Agenda sent to Dr. Smith at beginning of week 
  -  Dr. Smith's role will be primarily one of ADVISOR (advise on documentation, development process)
  - Development team will be primarily responsible for DESIGN, IMPLEMENTATION and DELIVERANCE of Final Product (naturally!)
-  Communication between Development Team and Dr. Smith via Issue Tracker (GitHub) and email as needed.

**Comment by smiths** [comment]
Hi James.  I like your summary.  However, this isn't really an issue.  After reading it, there is no clear task that needs to be accomplished to close the issue.

**Comment by littleappledev** [comment]
Thank you for letting me know. I will mark this Issue as Closed for the above reasons.
