### ISSUE TITLE
Select Coding Convention for C#

### ISSUE THREAD

**Issue by littleappledev** [sgao1995/Cat-and-Mouse-Game#13]
(Notes from Meeting #1) 
-  Development Team should agree upon a set of coding conventions for C#
  -  Will maximise code-readiblity and understandability in order to streamline development time.
-  Suggestions:  

1)  Microsoft C# Coding Conventions:  https://msdn.microsoft.com/en-us/library/ff926074.aspx
2)  Custom coding convention (agreed upon by entire Development Team)

**Comment by smiths** [comment]
This is a good issue.  If you wanted to, you could create a milestone for completing the development plan, and then this issue could be associated with that milestone.

**Comment by littleappledev** [comment]
Selected the **C# Coding Conventions (C# Programming Guide**) as outlined by **MSDN**.

A reference specification of this convention is available at:  https://msdn.microsoft.com/en-us/library/ff926074.aspx
