### ISSUE TITLE
Learn LaTeX

### ISSUE THREAD

**Issue by smiths** [sgao1995/Cat-and-Mouse-Game#5]
Any team members that are not familiar with LaTeX should do the lab exercise at:

https://gitlab.cas.mcmaster.ca/smiths/se3xa3/tree/master/Labs/L05

**Comment by littleappledev** [comment]
(Notes from Meeting #1)  
-  Also, no underlining as per Dr. Smith's recommendations!

**Comment by littleappledev** [comment]
As LaTeX was used to prepare the SRS document, I will assume that all group members are familar with the system  to the degree that is required for this project.

Thus, I will mark this Issue as "Closed".
